project:
  type: website

website:
  title: "E155 Project: RFID Jukebox"
  navbar:
    left:
      - href: index.qmd
        text: Project Overview
      - href: fpga.qmd
        text: FPGA Design
      - href: mcu.qmd
        text: MCU Design
      - href: results.qmd
        text: results
      - href: docs.qmd
        text: Documentation
      - href: team.qmd
        text: Team

format:
  html:
    theme:
      - united
      - brand
    css: styles.css
    toc: true



